#!/usr/bin/env python3
# mkgates.py -- vector gates for guest processes, generated from the
# base kernel's vector table.
#
#   mkgates.py base out.s out.lst
#
# For each gated vector the M68Kvec slot's current relocation target T
# (nullvect, an FPSP entry, isp61_vec) becomes:
#   guest_gate_N: native process -> jmp T; guest -> jmp guest_gate_c
# and guest_chain[N] = T for the gate's decline path.  Fault vectors
# first send supervisor-mode exceptions to T.  The A-line gate (10)
# sends a guest with GPF_ALINE to guest_linea, the fast reflection;
# gate 8 one with GPF_PRIV to guest_fpriv, the trap gates (but trap #0)
# one with GPF_FTRAP (trap #13: GPF_FTRAP13) to guest_ftrap.
# out.lst records "N T"
# for patch_vec.py.  Fails closed.
import sys
from elfrel import Elf

FAULTS = list(range(2, 12)) + list(range(48, 56)) + [60, 61]
TRAPS = list(range(32, 48))
GATED = sorted(FAULTS + TRAPS)
R_68K_32 = 1
P_EVPDP = 0xc8
GP_FLAGS_LSB = 15	# gp_flags, big-endian long at 12: GPF_ALINE is bit 0 here
ALINE = 10
PRIV = 8
GPF_PRIV_BIT = 1	# in the byte at 15
GPF_FTRAP_BIT = 0	# in the byte at 14; GPF_FTRAP13 is bit 1

e = Elf(sys.argv[1])
base = e.syms[e.sym('M68Kvec')]['value']
rel = e.text_relocs()
tgt = {}
for v in range(256):
    r = rel.get(base + 4 * v)
    if r:
        if r[2] != R_68K_32 or r[3] != 0:
            raise SystemExit('ABORT: M68Kvec[%d] relocation type %d addend %d' % (v, r[2], r[3]))
        tgt[v] = e.syms[r[1]]['name']
for v in GATED:
    t = tgt.get(v)
    if not t or t.startswith('guest_'):
        raise SystemExit('ABORT: M68Kvec[%d] target %r' % (v, t))
for v in (32, 42, 47):
    if tgt[v] != 'nullvect':
        raise SystemExit('ABORT: trap vector %d is %s, expected nullvect' % (v, tgt[v]))

s = ['| generated by mkgates.py from %s: do not edit' % sys.argv[1], '', '\t.text']
for v in GATED:
    t = tgt[v]
    s.append('\t.globl\tguest_gate_%d' % v)
    s.append('guest_gate_%d:' % v)
    if v in FAULTS:
        s += ['\tbtst\t&5,%sp@', '\tbeqw\tLu%d' % v, '\tjmp\t%s' % t, 'Lu%d:' % v]
    s += ['\tmovel\t%a0,%sp@-',
          '\tmoveal\tcurproc,%a0',
          '\ttstl\t%%a0@(%#x)' % P_EVPDP,
          '\tmoveal\t%sp@+,%a0',
          '\tbnew\tLg%d' % v,
          '\tjmp\t%s' % t,
          'Lg%d:' % v]
    if v == ALINE:
        s += ['\tmovel\t%a0,%sp@-',
              '\tmoveal\tcurproc,%a0',
              '\tmoveal\t%%a0@(%#x),%%a0' % P_EVPDP,
              '\tbtst\t&0,%%a0@(%d)' % GP_FLAGS_LSB,
              '\tmoveal\t%sp@+,%a0',
              '\tbnew\tguest_linea']
    if v == PRIV or (v in TRAPS and v != 32):
        if v == PRIV:
            off, bit, tgt_ = GP_FLAGS_LSB, GPF_PRIV_BIT, 'guest_fpriv'
        else:
            off, bit, tgt_ = GP_FLAGS_LSB - 1, GPF_FTRAP_BIT + (v == 45), 'guest_ftrap'
        s += ['\tmovel\t%a0,%sp@-',
              '\tmoveal\tcurproc,%a0',
              '\tmoveal\t%%a0@(%#x),%%a0' % P_EVPDP,
              '\tbtst\t&%d,%%a0@(%d)' % (bit, off),
              '\tmoveal\t%sp@+,%a0',
              '\tbnew\t%s' % tgt_]
    s += ['\tjmp\tguest_gate_c']
s += ['', '\t.data', '\t.globl\tguest_chain', 'guest_chain:']
for v in range(256):
    s.append('\t.long\t%s' % (tgt[v] if v in GATED else '0'))
open(sys.argv[2], 'w').write('\n'.join(s) + '\n')
open(sys.argv[3], 'w').write(''.join('%d %s\n' % (v, tgt[v]) for v in GATED))
print('mkgates: %d gates (%s)' % (len(GATED), ', '.join(sorted(set(tgt[v] for v in GATED)))))
