#!/usr/bin/env python3
# obj2s.py -- rewrite a data-only m68k ELF relocatable as assembler source.
#
#   obj2s.py in.o out.s [--drop-text] [--data-to-text START:END]
#            [--reloc OFF=SYM] [--drop-sym NAME]
#
# Every .data byte and R_68K_32 relocation is reproduced; symbols become
# labels, COMMON symbols .comm.  Edits:
#   --drop-text           omit the original .text (and its relocations)
#   --data-to-text S:E    move .data bytes [S,E) to .text, with their labels
#   --reloc OFF=SYM       make the .data relocation at OFF point at SYM
#   --drop-sym NAME       omit a symbol
import struct, sys

def u16(b, o): return struct.unpack('>H', b[o:o+2])[0]
def u32(b, o): return struct.unpack('>I', b[o:o+4])[0]

def load(path):
	b = open(path, 'rb').read()
	shoff, shn, shstr = u32(b, 32), u16(b, 48), u16(b, 50)
	secs = []
	for i in range(shn):
		o = shoff + i * 40
		secs.append(dict(name=u32(b, o), type=u32(b, o+4), off=u32(b, o+16),
			size=u32(b, o+20), link=u32(b, o+24), info=u32(b, o+28)))
	so = secs[shstr]['off']
	for s in secs:
		e = b.index(b'\0', so + s['name'])
		s['n'] = b[so + s['name']:e].decode()
	return b, secs

def fix(n):
	return n.replace('%', '_P')

def main():
	a = sys.argv[1:]
	src, out = a[0], a[1]
	droptext, move, rel, dropsym = False, None, {}, set()
	i = 2
	while i < len(a):
		if a[i] == '--drop-text': droptext = True
		elif a[i] == '--data-to-text':
			i += 1; s, e = a[i].split(':'); move = (int(s, 0), int(e, 0))
		elif a[i] == '--reloc':
			i += 1; o, s = a[i].split('='); rel[int(o, 0)] = s
		elif a[i] == '--drop-sym':
			i += 1; dropsym.add(a[i])
		i += 1

	b, secs = load(src)
	idx = {s['n']: n for n, s in enumerate(secs)}
	st = secs[idx['.symtab']]; strs = secs[st['link']]['off']
	syms = []
	for k in range(st['size'] // 16):
		o = st['off'] + k * 16
		nm = b[strs + u32(b, o):b.index(b'\0', strs + u32(b, o))].decode()
		syms.append(dict(name=nm, value=u32(b, o+4), size=u32(b, o+8),
			info=b[o+12], shndx=u16(b, o+14)))
	dsec = idx['.data']; tsec = idx['.text']
	data = b[secs[dsec]['off']:secs[dsec]['off'] + secs[dsec]['size']]
	text = b[secs[tsec]['off']:secs[tsec]['off'] + secs[tsec]['size']]
	if droptext or text.strip(b'\0') == b'':
		pass
	elif not droptext:
		sys.exit('obj2s: .text must be dropped (code is not rewritten)')

	relocs = {}
	rs = secs[idx['.rela.data']]
	for k in range(rs['size'] // 12):
		o = rs['off'] + k * 12
		off, info, add = u32(b, o), u32(b, o+4), struct.unpack('>i', b[o+8:o+12])[0]
		if info & 0xff != 1: sys.exit('obj2s: unsupported relocation type')
		s = syms[info >> 8]
		name = s['name']
		if (s['info'] & 0xf) == 3:	# section symbol
			name = {dsec: '.Ldata', tsec: '.Ltext'}[s['shndx']]
		relocs[off] = (rel.get(off, fix(name)), add)

	labels = {}
	glob = set()
	for s in syms:
		t, bind = s['info'] & 0xf, s['info'] >> 4
		if not s['name'] or t in (3, 4) or s['name'] in dropsym: continue
		if bind == 1: glob.add(s['name'])
		if s['shndx'] == dsec:
			labels.setdefault(s['value'], []).append(fix(s['name']))
	comms = [s for s in syms if s['shndx'] == 0xfff2 and s['name'] not in dropsym]

	w = open(out, 'w')
	w.write('| generated by obj2s.py from %s\n' % src.split('/')[-1])
	for g in sorted(glob): w.write('\t.globl\t%s\n' % g)

	def emit(lo, hi, lbase):
		p = lo
		while p < hi:
			for l in labels.get(p, []): w.write('%s:\n' % l)
			if p in relocs:
				s, ad = relocs[p]
				if s == '.Ldata' and move and move[0] <= ad < move[1]:
					s, ad = '.Ltext', ad - move[0]
				elif s == '.Ldata' and move and ad >= move[1]:
					ad -= move[1] - move[0]
				w.write('\t.long\t%s%s\n' % (s, ('+%d' % ad) if ad else ''))
				p += 4
			else:
				w.write('\t.byte\t%d\n' % data[p]); p += 1

	w.write('\t.text\n.Ltext:\n')
	if move: emit(move[0], move[1], move[0])
	w.write('\t.data\n.Ldata:\n')
	if move:
		emit(0, move[0], 0); emit(move[1], len(data), 0)
	else:
		emit(0, len(data), 0)
	for s in syms:
		if s['shndx'] == dsec and s['size'] and s['name'] not in dropsym and (s['info'] & 0xf) == 1:
			w.write('\t.type\t%s,@object\n\t.size\t%s,%d\n' % (fix(s['name']), fix(s['name']), s['size']))
	for s in comms: w.write('\t.comm\t%s,%d,%d\n' % (s['name'], s['size'], s['value']))
	w.close()

main()
