#!/usr/bin/env python3
# mkfont.py -- 8x16 console font for fbcons from an X11 PCF bitmap font.
#
#   python3 mkfont.py [-o fbfont.c] [--check fbfont.c] [font.pcf[.gz]]
#
# Default input: the Sony 8x16 ISO 8859-1 font of X11 (xfonts-base,
# /usr/share/fonts/X11/misc/8x16.pcf.gz).  Any PCF font whose glyphs fit
# an 8x16 cell works; smaller fonts are placed by their ascent (the
# public-domain misc-fixed 8x13 gives a 1-row top, 2-row bottom margin).
# The output is fb_font[256][16]: one byte per row, bit 7 = leftmost
# pixel, row 0 at the top.  Codes with no glyph are blank.
# --check regenerates and compares with an existing fbfont.c.
import gzip, hashlib, struct, sys

W, H = 8, 16
PCF_METRICS, PCF_BITMAPS, PCF_BDF_ENCODINGS = 1 << 2, 1 << 3, 1 << 5
PCF_ACCELERATORS, PCF_BDF_ACCELERATORS, PCF_PROPERTIES = 1 << 1, 1 << 8, 1
PCF_COMPRESSED_METRICS = 0x100


def load(path):
    raw = open(path, 'rb').read()
    return gzip.decompress(raw) if raw[:2] == b'\x1f\x8b' else raw


class Table:
    def __init__(self, d, off):
        self.d, self.fmt = d, struct.unpack('<I', d[off:off + 4])[0]
        self.o = off + 4
        self.e = '>' if self.fmt & 4 else '<'

    def get(self, f):
        n = struct.calcsize(self.e + f)
        v = struct.unpack(self.e + f, self.d[self.o:self.o + n])
        self.o += n
        return v if len(v) > 1 else v[0]


def parse(d):
    if d[:4] != b'\x01fcp':
        raise SystemExit('not a PCF font')
    n = struct.unpack('<I', d[4:8])[0]
    tabs = {}
    for i in range(n):
        t, f, s, o = struct.unpack('<4I', d[8 + 16 * i:24 + 16 * i])
        tabs[t] = o
    # properties: copyright and name strings
    props = {}
    t = Table(d, tabs[PCF_PROPERTIES])
    np = t.get('i')
    pl = [t.get('iBi') for _ in range(np)]
    t.o += (4 - (np & 3)) & 3
    ssz = t.get('i')
    strs = d[t.o:t.o + ssz]
    cstr = lambda k: strs[k:strs.index(b'\0', k)].decode('latin1')
    for name, isstr, val in pl:
        props[cstr(name)] = cstr(val) if isstr else val
    # ascent from the accelerator table
    t = Table(d, tabs.get(PCF_BDF_ACCELERATORS, tabs.get(PCF_ACCELERATORS)))
    t.o += 8
    fasc, fdesc = t.get('i'), t.get('i')
    # metrics
    t = Table(d, tabs[PCF_METRICS])
    mets = []
    if t.fmt & PCF_COMPRESSED_METRICS:
        for _ in range(t.get('h')):
            l, r, w, a, de = [x - 0x80 for x in t.get('5B')]
            mets.append((l, r, w, a, de))
    else:
        for _ in range(t.get('i')):
            l, r, w, a, de, _attr = t.get('5hH')
            mets.append((l, r, w, a, de))
    # bitmaps
    t = Table(d, tabs[PCF_BITMAPS])
    ng = t.get('i')
    offs = [t.get('i') for _ in range(ng)]
    t.o += 16
    base = t.o
    pad = 1 << (t.fmt & 3)
    msbit = bool(t.fmt & 8)
    glyphs = []
    for g in range(ng):
        l, r, w, a, de = mets[g]
        gw, gh = r - l, a + de
        stride = ((gw + 7) // 8 + pad - 1) // pad * pad
        rows = []
        for y in range(gh):
            p = base + offs[g] + y * stride
            bits = []
            for x in range(gw):
                b = d[p + x // 8]
                bits.append((b >> (7 - x % 8)) & 1 if msbit else (b >> (x % 8)) & 1)
            rows.append(bits)
        glyphs.append((l, a, rows))
    # encodings
    t = Table(d, tabs[PCF_BDF_ENCODINGS])
    min2, max2, min1, max1, _dflt = t.get('5h')
    enc = {}
    for b1 in range(min1, max1 + 1):
        for b2 in range(min2, max2 + 1):
            gi = t.get('H')
            if gi != 0xFFFF:
                enc[(b1 << 8) | b2] = gi
    return props, fasc, fdesc, glyphs, enc


def build(path):
    props, fasc, fdesc, glyphs, enc = parse(load(path))
    if fasc + fdesc > H:
        raise SystemExit('font is %d rows high' % (fasc + fdesc))
    top = (H - fasc - fdesc) // 2      # extra rows above
    font = [[0] * H for _ in range(256)]
    for c in range(256):
        if c not in enc:
            continue
        lsb, asc, rows = glyphs[enc[c]]
        for y, bits in enumerate(rows):
            cy = top + fasc - asc + y
            for x, b in enumerate(bits):
                cx = lsb + x
                if b and 0 <= cx < W and 0 <= cy < H:
                    font[c][cy] |= 0x80 >> cx
                elif b:
                    raise SystemExit('glyph %#x does not fit the cell' % c)
    return props, font


def emit(path, props, font):
    src = open(path, 'rb').read()
    out = []
    out.append('/*\n * fbfont.c -- 8x16 console font, generated by mkfont.py; do not edit.\n *')
    out.append(' * Source: %s' % path.split('/')[-1])
    out.append(' *   %s' % props.get('FONT', '?'))
    out.append(' *   sha256 %s' % hashlib.sha256(src).hexdigest())
    for k in ('COPYRIGHT', 'NOTICE'):
        if k in props:
            out.append(' *   %s: %s' % (k, props[k]))
    out.append(' * Licence of the source font: see NOTES.md (Font).')
    out.append(' * fb_font[c][row]: bit 7 is the leftmost pixel, row 0 the top.\n */\n')
    out.append('unsigned char fb_font[256][16] = {')
    for c in range(256):
        name = repr(chr(c)) if 0x20 < c < 0x7F else '0x%02x' % c
        out.append('\t{ %s },\t/* %s */' % (', '.join('0x%02x' % v for v in font[c]), name))
    out.append('};')
    return '\n'.join(out) + '\n'


def main(a):
    outp, check, src = None, None, '/usr/share/fonts/X11/misc/8x16.pcf.gz'
    while a:
        if a[0] == '-o':
            outp, a = a[1], a[2:]
        elif a[0] == '--check':
            check, a = a[1], a[2:]
        else:
            src, a = a[0], a[1:]
    props, font = build(src)
    text = emit(src, props, font)
    if check:
        ok = open(check).read() == text
        print('%s: %s' % (check, 'matches the source font' if ok else 'DIFFERS'))
        return 0 if ok else 1
    if outp:
        open(outp, 'w').write(text)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
