#!/usr/bin/env python3
# mkapi.py -- the Win16 environment's table of every export of the system
# modules (ordinal, name, argument words, return size), from Wine's
# 16-bit .spec files (LGPL-2.1; interface facts only).
#
#   python3 mkapi.py WINE_DLLS_DIR > apitab.c
#
# Our own implementations are bound to these entries by name at start
# (thunk.c); an entry without one stops the program with its name, and
# its argument bytes say how much stack a call takes.
import os, re, sys

MODS = [
    ('KERNEL', 'krnl386.exe16'), ('USER', 'user.exe16'), ('GDI', 'gdi.exe16'),
    ('KEYBOARD', 'keyboard.drv16'), ('SYSTEM', 'system.drv16'), ('SOUND', 'sound.drv16'),
    ('WIN87EM', 'win87em.dll16'), ('TOOLHELP', 'toolhelp.dll16'), ('MMSYSTEM', 'mmsystem.dll16'),
    ('SHELL', 'shell.dll16'), ('COMMDLG', 'commdlg.dll16'), ('VER', 'ver.dll16'),
    ('LZEXPAND', 'lzexpand.dll16'), ('DISPLAY', 'display.drv16'), ('MOUSE', 'mouse.drv16'),
    ('DDEML', 'ddeml.dll16'), ('WINSOCK', 'winsock.dll16'), ('COMPOBJ', 'compobj.dll16'),
    ('OLE2', 'ole2.dll16'),
]
ARG = {'word': 'w', 's_word': 's', 'long': 'l', 'ptr': 'p', 'str': 'p', 'segptr': 'p', 'segstr': 'p', 'int64': 'q', 'double': 'q'}
LINE = re.compile(r'^(\d+)\s+(pascal|cdecl|varargs|stub|equate|variable)\s*(.*)$')


def parse(path):
    out = []
    for line in open(path):
        line = line.split('#', 1)[0].strip()
        m = LINE.match(line)
        if not m:
            continue
        ordn, kind, rest = int(m.group(1)), m.group(2), m.group(3)
        flags = []
        while rest.startswith('-'):
            f, rest = rest.split(None, 1)
            flags.append(f)
        if kind == 'stub':
            out.append((ordn, rest.split()[0], 's', '', 'l'))
        elif kind == 'equate':
            name, val = rest.split()[:2]
            out.append((ordn, name, 'e', str(int(val, 0)), 'w'))
        elif kind == 'variable':
            name = rest.split('(')[0].strip()
            vals = rest.split('(', 1)[1].split(')')[0].split()
            out.append((ordn, name, 'V', ' '.join(str(int(v, 0)) for v in vals), 'l'))
        else:
            name = rest.split('(')[0].strip()
            args = rest.split('(', 1)[1].split(')')[0].split()
            a = ''.join(ARG[x] for x in args)
            k = {'pascal': 'p', 'cdecl': 'c', 'varargs': 'v'}[kind]
            if '-register' in flags:
                k = 'r'
            out.append((ordn, name, k, a, 'w' if '-ret16' in flags else 'l'))
    return sorted(out)


def main():
    src = sys.argv[1]
    print('/*\n * apitab.c -- every export of the system modules, generated by mkapi.py'
          '\n * from Wine\'s 16-bit .spec files (LGPL-2.1); do not edit.'
          '\n *\n * kind: p pascal, c cdecl, v varargs, r register, s stub (arguments unknown),'
          '\n * e equate (args: value), V variable (args: its dwords).'
          '\n * args: w word, s signed word, l long, p far pointer, q 8 bytes; first argument first.'
          '\n * ret: w AX, l DX:AX.\n */\n\n#include "apitab.h"\n')
    for mod, d in MODS:
        ents = parse(os.path.join(src, d, d + '.spec'))
        print('static struct apient a_%s[] = {' % mod)
        for o, n, k, a, r in ents:
            print('\t{ %d, "%s", \'%s\', "%s", \'%s\' },' % (o, n, k, a, r))
        print('\t{ 0 }\n};\n')
    print('struct apimod apimods[] = {')
    for mod, d in MODS:
        print('\t{ "%s", a_%s },' % (mod, mod))
    print('\t{ 0 }\n};')


main()
