#!/usr/bin/env python3
# mkfonts.py -- the Win16 environment's built-in bitmap fonts, from X.Org's
# Adobe 100dpi PCF fonts (xfonts-100dpi; licence in NOTES.md, Fonts).
#
#   python3 mkfonts.py PCF_DIR > fonts.c
#
# A small set built in; more sizes can come as .FNT files.  Each glyph is a cell as wide as its advance and as high as the font,
# rows of (w+7)/8 bytes, bit 7 leftmost.  Characters 0x20-0xff, Windows
# ANSI being ISO 8859-1 there but for 0x80-0x9f, which get the default.
import gzip, hashlib, os, struct, sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '../../mac/video'))
import mkfont

# face, file, point size, weight, italic, pitch (1 fixed), family (FF_*)
FONTS = [
    ('Helv', 'helvR08', 8, 400, 0, 0, 0x20), ('Helv', 'helvR10', 10, 400, 0, 0, 0x20),
    ('Helv', 'helvR12', 12, 400, 0, 0, 0x20), ('Helv', 'helvR14', 14, 400, 0, 0, 0x20),
    ('Helv', 'helvB10', 10, 700, 0, 0, 0x20), ('Helv', 'helvB12', 12, 700, 0, 0, 0x20),
    ('Tms Rmn', 'timR10', 10, 400, 0, 0, 0x10), ('Tms Rmn', 'timR12', 12, 400, 0, 0, 0x10),
    ('Tms Rmn', 'timB12', 12, 700, 0, 0, 0x10),
    ('Courier', 'courR10', 10, 400, 0, 1, 0x30), ('Courier', 'courR12', 12, 400, 0, 1, 0x30),
]


def parse(d):
    """mkfont.parse, plus each glyph's advance width"""
    props, fasc, fdesc, glyphs, enc = mkfont.parse(d)
    n = struct.unpack('<I', d[4:8])[0]
    tabs = {}
    for i in range(n):
        t, f, s, o = struct.unpack('<4I', d[8 + 16 * i:24 + 16 * i])
        tabs[t] = o
    t = mkfont.Table(d, tabs[mkfont.PCF_METRICS])
    adv = []
    if t.fmt & mkfont.PCF_COMPRESSED_METRICS:
        for _ in range(t.get('h')):
            adv.append(t.get('5B')[2] - 0x80)
    else:
        for _ in range(t.get('i')):
            adv.append(t.get('5hH')[2])
    return props, fasc, fdesc, glyphs, enc, adv


def build(path):
    d = mkfont.load(path)
    props, asc, desc, glyphs, enc, adv = parse(d)
    h = asc + desc
    dflt = enc.get(ord('?'))
    out = []
    for c in range(0x20, 0x100):
        gi = enc.get(c)
        if gi is None or (0x80 <= c < 0xa0):
            gi = dflt if c != 0x20 else enc.get(0x20)
        w = adv[gi]
        lsb, gasc, rows = glyphs[gi]
        cell = [[0] * w for _ in range(h)]
        for y, bits in enumerate(rows):
            cy = asc - gasc + y
            for x, b in enumerate(bits):
                cx = lsb + x
                if b and 0 <= cy < h:
                    cx = min(max(cx, 0), w - 1) if w else 0
                    if w:
                        cell[cy][cx] = 1
        out.append((w, cell))
    return props, asc, desc, out, hashlib.sha256(open(path, 'rb').read()).hexdigest()


def main():
    src = sys.argv[1]
    print('/*\n * fonts.c -- built-in bitmap fonts, generated by mkfonts.py from X.Org\'s'
          '\n * Adobe 100dpi fonts (xfonts-100dpi); do not edit.  Licence: NOTES.md, Fonts.'
          '\n *\n * Copyright 1984-1989, 1994 Adobe Systems Incorporated.'
          '\n * Copyright 1988, 1994 Digital Equipment Corporation.\n */\n\n#include "font.h"\n')
    names = []
    for face, f, pt, wt, it, pitch, fam in FONTS:
        props, asc, desc, glyphs, sha = build(os.path.join(src, f + '-ISO8859-1.pcf.gz'))
        nm = f
        names.append(nm)
        bits, offs, wid = [], [], []
        for w, cell in glyphs:
            offs.append(len(bits))
            wid.append(w)
            bpr = (w + 7) // 8
            for row in cell:
                for b in range(bpr):
                    v = 0
                    for x in range(8):
                        if b * 8 + x < w and row[b * 8 + x]:
                            v |= 0x80 >> x
                    bits.append(v)
        ws = [w for w, _ in glyphs]
        avg = sum(ws[0x61 - 0x20:0x7b - 0x20]) * 10 // 26 // 10 if not pitch else ws[0x41 - 0x20]
        print('/* %s %s.pcf.gz sha256 %s */' % (props.get('FONT', '?'), f, sha))
        print('static unsigned char b_%s[] = {' % nm)
        for i in range(0, len(bits), 16):
            print('\t' + ', '.join('0x%02x' % v for v in bits[i:i + 16]) + ',')
        print('};')
        print('static unsigned short o_%s[] = {' % nm)
        for i in range(0, len(offs), 12):
            print('\t' + ', '.join(str(v) for v in offs[i:i + 12]) + ',')
        print('};')
        print('static unsigned char w_%s[] = {' % nm)
        for i in range(0, len(wid), 16):
            print('\t' + ', '.join(str(v) for v in wid[i:i + 16]) + ',')
        print('};\n')
        print('#define F_%s { "%s", %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, 0x20, 0xff, w_%s, o_%s, b_%s }\n'
              % (nm, face, pt, asc + desc, asc, desc, wt, it, pitch, fam, avg, max(ws), nm, nm, nm))
    print('struct bfont bfonts[] = {')
    for nm in names:
        print('\tF_%s,' % nm)
    print('\t{ 0 }\n};')


main()
